import { ref, computed } from 'vue'

const lang = ref(localStorage.getItem('qrpay-lang') || 'tr')

export function setLang(l) {
  lang.value = l
  localStorage.setItem('qrpay-lang', l)
}

export { lang }

const messages = {
  tr: {
    // AppShell
    appName: 'QRPay',
    panelName: 'Kiosk Paneli',
    expandSidebar: 'Kenar çubuğunu genişlet',
    collapseSidebar: 'Kenar çubuğunu daralt',
    nav: {
      dashboard: 'Panel',
      tables: 'Masalar',
      orders: 'Siparişler',
      cashier: 'Kasa',
      menu: 'Menü',
      staff: 'Personel',
      settings: 'Ayarlar',
    },
    darkMode: 'Karanlık mod',
    lightMode: 'Aydınlık mod',
    dark: 'Koyu',
    light: 'Açık',
    signOut: 'Çıkış yap',

    // Login
    loginTagline: 'İşletmenizi tek panelden yönetin. Masalar, siparişler, kasa ve menü — hepsi burada.',
    welcomeBack: 'Tekrar hoş geldiniz',
    signInToAccount: 'Hesabınıza giriş yapın',
    enterCredentials: 'Devam etmek için bilgilerinizi girin',
    username: 'Kullanıcı adı',
    usernamePlaceholder: 'admin',
    password: 'Şifre',
    passwordPlaceholder: 'Şifrenizi girin',
    forgotPassword: 'Unuttum?',
    signingIn: 'Giriş yapılıyor...',
    signIn: 'Giriş Yap',

    // Dashboard
    occupiedTables: 'Dolu Masa',
    activeOrders: 'Aktif Sipariş',
    dailyRevenue: 'Günlük Ciro',
    guests: 'Misafir',
    activeTables: 'Açık Masalar',
    viewAll: 'Tümünü Gör',
    recentOrders: 'Son Siparişler',
    noActiveTables: 'Açık masa yok',
    noOrdersToday: 'Bugün sipariş yok',
    tableStatus: {
      OPEN: 'Açık',
      WAITING: 'Bekliyor',
      empty: 'Boş',
      open: 'Açık',
      waiting: 'Bekliyor',
      payment: 'Ödeme',
    },
    orderStatus: {
      PENDING_APPROVAL: 'Onay Bekliyor',
      APPROVED: 'Hazırlanıyor',
      SERVED: 'Servis Edildi',
      CANCELLED: 'İptal',
    },

    // Tables
    tablesTitle: 'Masalar',
    tablesSubtitle: 'Restoran zeminini yönetin',
    exitFullscreen: 'Tam ekrandan çık',
    enterFullscreen: 'Tam ekrana geç',
    addTable: 'Masa Ekle',
    available: 'Müsait',
    tableAvailable: 'Masa müsait',
    noActiveSession: 'Bu masada aktif oturum yok.',
    openTable: 'Masa Aç',
    tableLabel: 'Masa',
    guestsLabel: 'Misafir',
    openedLabel: 'Açıldı',
    totalLabel: 'Toplam',
    customerPin: 'Müşteri PIN',
    pinHint: 'Müşteri QR kodu okuttuktan sonra bu PIN\'i söyleyin.',
    ordersLabel: 'Siparişler',
    printQr: 'QR Yazdır',
    closeBill: 'Hesabı Kapat',
    enterPin: 'PIN Girin',
    enterPinToExit: 'Tam ekrandan çıkmak için PIN\'inizi girin',
    incorrectPin: 'Hatalı PIN. Tekrar deneyin.',
    cancel: 'İptal',
    tableOpened: 'Masa açıldı',
    tableClosed: 'Hesap kapatıldı',
    tableAdded: 'Masa eklendi',
    tableDuplicate: 'Bu numara zaten mevcut',
    tableNumber: 'Masa Numarası',
    tableLabelInput: 'Etiket (opsiyonel)',
    tableLabelInputPlaceholder: 'örn: Bahçe',
    tableCapacity: 'Kapasite',
    addTableTitle: 'Yeni Masa Ekle',
    adding: 'Ekleniyor...',
    enterOrder: 'Sipariş Gir',
    orderEntryTitle: 'Sipariş Oluştur',
    allItems: 'Tümü',
    cartEmpty: 'Sepet boş — ürün seçin',
    submitOrder: 'Siparişi Gönder',
    submitting: 'Gönderiliyor...',
    orderSent: 'Sipariş gönderildi',

    // Orders
    ordersTitle: 'Siparişler',
    ordersSubtitle: 'Gelen siparişleri takip edin ve yönetin',
    filterAll: 'Tümü',
    filterNew: 'Yeni',
    filterPreparing: 'Hazırlanıyor',
    filterDelivered: 'Teslim Edildi',
    noOrdersFound: 'Sipariş bulunamadı',
    noOrdersHint: 'Filtrenize uyan siparişler burada görünecek',
    approve: 'Onayla',
    reject: 'Reddet',
    markDelivered: 'Teslim Edildi',

    // Menu
    menuTitle: 'Menü',
    menuSubtitle: 'Ürünleri ve kategorileri yönetin',
    addItem: 'Ürün Ekle',
    categories: 'Kategoriler',
    addCategory: 'Kategori',
    edit: 'Düzenle',
    editItem: 'Ürünü Düzenle',
    newItem: 'Yeni Ürün',
    itemName: 'Ürün Adı',
    itemNamePlaceholder: 'Adana Kebap',
    priceTL: 'Fiyat (TL)',
    description: 'Açıklama',
    descriptionPlaceholder: 'Ürün açıklaması...',
    station: 'İstasyon',
    kitchen: 'Mutfak',
    bar: 'Bar',
    categoryLabel: 'Kategori',
    save: 'Kaydet',
    active: 'Aktif',
    inactive: 'Pasif',
    requiresApproval: 'Onay Gereksin',
    requiresApprovalHint: 'Bu ürünü içeren siparişler kiosk onayına düşer',

    // Staff
    staffTitle: 'Personel',
    staffSubtitle: 'Ekip üyelerini ve rolleri yönetin',
    addStaff: 'Personel Ekle',
    name: 'Ad',
    email: 'E-posta',
    role: 'Rol',
    lastLogin: 'Son Giriş',
    actions: 'İşlemler',

    // Cashier
    cashierTitle: 'Kasa',
    cashierSubtitle: 'Ödemeleri işleyin ve hesapları kapatın',
    openBills: 'Açık Hesaplar',
    selectBill: 'Hesap seçin',
    selectBillHint: 'Sol panelden açık bir hesap seçin',
    subtotal: 'Ara Toplam',
    vat: 'KDV',
    total: 'Toplam',
    paymentMethod: 'Ödeme Yöntemi',
    cash: 'Nakit',
    card: 'Kart',

    // Settings
    settingsTitle: 'Ayarlar',
    settingsSubtitle: 'İşletme tercihlerinizi yapılandırın',
    saveChanges: 'Değişiklikleri Kaydet',
    saved: 'Kaydedildi',
    tabs: {
      brand: 'Marka',
      finance: 'Finans',
      notifications: 'Diğer',
    },
    brandSettings: 'Marka Ayarları',
    brandSettingsDesc: 'Marka kimliğinizi özelleştirin',
    businessName: 'İşletme Adı',
    logo: 'Logo',
    uploadPhoto: 'Fotoğraf Yükle',
    uploadHint: 'PNG, JPG maks. 2MB',
    primaryColor: 'Ana Renk',
    secondaryColor: 'İkincil Renk',
    themeLabel: 'Tema',
    financeSettings: 'Finans Ayarları',
    financeSettingsDesc: 'Para birimi, vergi ve fiş ayarlarını yapılandırın',
    currency: 'Para Birimi',
    vatRate: 'KDV Oranı (%)',
    vatMode: 'KDV Modu',
    inclusive: 'Dahil',
    exclusive: 'Hariç',
    receiptPrefix: 'Fiş Öneki (isteğe bağlı)',
    receiptPrefixPlaceholder: 'örn. BAR',
    receiptPrefixHint: 'Örnek: BAR-20260415-0001',
    otherSettings: 'Diğer Ayarlar',
    otherSettingsDesc: 'Dil, bildirim ve sipariş ayarları',
    defaultLanguage: 'Varsayılan Dil',
    turkish: 'Türkçe',
    english: 'İngilizce',
    soundNotif: 'Sesli Bildirim',
    soundNotifDesc: 'Yeni siparişte ses çal',
    visualNotif: 'Görsel Bildirim',
    visualNotifDesc: 'Ekranda popup göster',
    orderApproval: 'Sipariş Onayı',
    orderApprovalOn: 'Müşteri siparişleri kiosk onayı bekler',
    orderApprovalOff: 'Müşteri siparişleri direkt mutfağa düşer',
  },

  en: {
    // AppShell
    appName: 'QRPay',
    panelName: 'Kiosk Panel',
    expandSidebar: 'Expand sidebar',
    collapseSidebar: 'Collapse sidebar',
    nav: {
      dashboard: 'Dashboard',
      tables: 'Tables',
      orders: 'Orders',
      cashier: 'Cashier',
      menu: 'Menu',
      staff: 'Staff',
      settings: 'Settings',
    },
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    dark: 'Dark',
    light: 'Light',
    signOut: 'Sign out',

    // Login
    loginTagline: 'Manage your business from a single panel. Tables, orders, cashier and menu — all here.',
    welcomeBack: 'Welcome back',
    signInToAccount: 'Sign in to your account',
    enterCredentials: 'Enter your credentials to continue',
    username: 'Username',
    usernamePlaceholder: 'admin',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    forgotPassword: 'Forgot?',
    signingIn: 'Signing in...',
    signIn: 'Sign In',

    // Dashboard
    occupiedTables: 'Occupied Tables',
    activeOrders: 'Active Orders',
    dailyRevenue: 'Daily Revenue',
    guests: 'Guests',
    activeTables: 'Active Tables',
    viewAll: 'View All',
    recentOrders: 'Recent Orders',
    noActiveTables: 'No open tables',
    noOrdersToday: 'No orders today',
    tableStatus: {
      OPEN: 'Open',
      WAITING: 'Waiting',
      empty: 'Empty',
      open: 'Open',
      waiting: 'Waiting',
      payment: 'Payment',
    },
    orderStatus: {
      PENDING_APPROVAL: 'Pending Approval',
      APPROVED: 'Preparing',
      SERVED: 'Served',
      CANCELLED: 'Cancelled',
    },

    // Tables
    tablesTitle: 'Tables',
    tablesSubtitle: 'Manage your restaurant floor',
    exitFullscreen: 'Exit fullscreen',
    enterFullscreen: 'Enter fullscreen',
    addTable: 'Add Table',
    available: 'Available',
    tableAvailable: 'Table is available',
    noActiveSession: 'No active session at this table.',
    openTable: 'Open Table',
    tableLabel: 'Table',
    guestsLabel: 'Guests',
    openedLabel: 'Opened',
    totalLabel: 'Total',
    customerPin: 'Customer PIN',
    pinHint: 'Tell this PIN to the customer after they scan the QR.',
    ordersLabel: 'Orders',
    printQr: 'Print QR',
    closeBill: 'Close Bill',
    enterPin: 'Enter PIN',
    enterPinToExit: 'Enter your PIN to exit fullscreen',
    incorrectPin: 'Incorrect PIN. Try again.',
    cancel: 'Cancel',
    tableOpened: 'Table opened',
    tableClosed: 'Bill closed',
    tableAdded: 'Table added',
    tableDuplicate: 'This number already exists',
    tableNumber: 'Table Number',
    tableLabelInput: 'Label (optional)',
    tableLabelInputPlaceholder: 'e.g. Garden',
    tableCapacity: 'Capacity',
    addTableTitle: 'Add New Table',
    adding: 'Adding...',
    enterOrder: 'Enter Order',
    orderEntryTitle: 'Create Order',
    allItems: 'All',
    cartEmpty: 'Cart is empty — select items',
    submitOrder: 'Submit Order',
    submitting: 'Submitting...',
    orderSent: 'Order sent',

    // Orders
    ordersTitle: 'Orders',
    ordersSubtitle: 'Track and manage incoming orders',
    filterAll: 'All',
    filterNew: 'New',
    filterPreparing: 'Preparing',
    filterDelivered: 'Delivered',
    noOrdersFound: 'No orders found',
    noOrdersHint: 'Orders matching your filter will appear here',
    approve: 'Approve',
    reject: 'Reject',
    markDelivered: 'Mark as Delivered',

    // Menu
    menuTitle: 'Menu',
    menuSubtitle: 'Manage your products and categories',
    addItem: 'Add Item',
    categories: 'Categories',
    addCategory: 'Category',
    edit: 'Edit',
    editItem: 'Edit Item',
    newItem: 'New Item',
    itemName: 'Item Name',
    itemNamePlaceholder: 'Adana Kebap',
    priceTL: 'Price (TL)',
    description: 'Description',
    descriptionPlaceholder: 'Product description...',
    station: 'Station',
    kitchen: 'Kitchen',
    bar: 'Bar',
    categoryLabel: 'Category',
    save: 'Save',
    active: 'Active',
    inactive: 'Inactive',
    requiresApproval: 'Requires Approval',
    requiresApprovalHint: 'Orders containing this item will require kiosk approval',

    // Staff
    staffTitle: 'Staff',
    staffSubtitle: 'Manage team members and roles',
    addStaff: 'Add Staff',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    lastLogin: 'Last Login',
    actions: 'Actions',

    // Cashier
    cashierTitle: 'Cashier',
    cashierSubtitle: 'Process payments and close bills',
    openBills: 'Open Bills',
    selectBill: 'Select a bill',
    selectBillHint: 'Choose an open bill from the left panel',
    subtotal: 'Subtotal',
    vat: 'VAT',
    total: 'Total',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',

    // Settings
    settingsTitle: 'Settings',
    settingsSubtitle: 'Configure your business preferences',
    saveChanges: 'Save Changes',
    saved: 'Saved',
    tabs: {
      brand: 'Brand',
      finance: 'Finance',
      notifications: 'Others',
    },
    brandSettings: 'Brand Settings',
    brandSettingsDesc: 'Customize your brand identity',
    businessName: 'Business Name',
    logo: 'Logo',
    uploadPhoto: 'Upload Photo',
    uploadHint: 'PNG, JPG up to 2MB',
    primaryColor: 'Primary Color',
    secondaryColor: 'Secondary Color',
    themeLabel: 'Theme',
    financeSettings: 'Finance Settings',
    financeSettingsDesc: 'Configure currency, tax, and receipt settings',
    currency: 'Currency',
    vatRate: 'VAT Rate (%)',
    vatMode: 'VAT Mode',
    inclusive: 'Inclusive',
    exclusive: 'Exclusive',
    receiptPrefix: 'Receipt Prefix (optional)',
    receiptPrefixPlaceholder: 'e.g. BAR',
    receiptPrefixHint: 'Example: BAR-20260415-0001',
    otherSettings: 'Other Settings',
    otherSettingsDesc: 'Language, notifications, and order settings',
    defaultLanguage: 'Default Language',
    turkish: 'Turkish',
    english: 'English',
    soundNotif: 'Sound Notifications',
    soundNotifDesc: 'Play sound on new order',
    visualNotif: 'Visual Notifications',
    visualNotifDesc: 'Show popup on screen',
    orderApproval: 'Order Approval',
    orderApprovalOn: 'Customer orders wait for kiosk approval',
    orderApprovalOff: 'Customer orders go directly to kitchen',
  },
}

export const t = computed(() => messages[lang.value] || messages.tr)
